
epoch 0
  0%|                                                                                                                              | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/scripts/train.py", line 67, in <module>
    main(
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/scripts/train.py", line 55, in main
    trainer.train()
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/scripts/trainer.py", line 35, in train
    for batch in tqdm(self.dataloader_train):
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/.venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/.venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ericbunch/wb-dev/layoutlm_sroie_demo/.venv/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
IndexError: list index out of range